use super::{Category, ConversionFunction, ConversionFunctionMap};
use std::{collections::HashMap, convert::identity};
use unit_conversions::data_transfer_rate::*;

const BITS_PER_SECOND: &str = "bits-per-second";
const GIGABITS_PER_SECOND: &str = "gigabits-per-second";
const GIGABYTES_PER_SECOND: &str = "gigabytes-per-second";
const KIBIBITS_PER_SECOND: &str = "kibibits-per-second";
const KILOBITS_PER_SECOND: &str = "kilobits-per-second";
const KILOBYTES_PER_SECOND: &str = "kilobytes-per-second";
const MEBIBITS_PER_SECOND: &str = "mebibits-per-second";
const MEGABITS_PER_SECOND: &str = "megabits-per-second";
const MEGABYTES_PER_SECOND: &str = "megabytes-per-second";
const TERABITS_PER_SECOND: &str = "terabits-per-second";
const TERABYTES_PER_SECOND: &str = "terabytes-per-second";

pub struct DataTransferRate;

impl Category for DataTransferRate {
    fn name() -> &'static str {
        "data-transfer-rate"
    }
    fn conversion_function_map() -> ConversionFunctionMap {
        HashMap::from_iter([
            (
                BITS_PER_SECOND,
                HashMap::from_iter([
                    (BITS_PER_SECOND, identity as ConversionFunction),
                    (
                        GIGABITS_PER_SECOND,
                        bits_per_second::to_giga_bits_per_second,
                    ),
                    (
                        GIGABYTES_PER_SECOND,
                        bits_per_second::to_giga_bytes_per_second,
                    ),
                    (KIBIBITS_PER_SECOND, bits_per_second::to_kibibits_per_second),
                    (
                        KILOBITS_PER_SECOND,
                        bits_per_second::to_kilo_bits_per_second,
                    ),
                    (
                        KILOBYTES_PER_SECOND,
                        bits_per_second::to_kilo_bytes_per_second,
                    ),
                    (MEBIBITS_PER_SECOND, bits_per_second::to_mebibits_per_second),
                    (
                        MEGABITS_PER_SECOND,
                        bits_per_second::to_mega_bits_per_second,
                    ),
                    (
                        MEGABYTES_PER_SECOND,
                        bits_per_second::to_mega_bytes_per_second,
                    ),
                    (
                        TERABITS_PER_SECOND,
                        bits_per_second::to_tera_bits_per_second,
                    ),
                    (
                        TERABYTES_PER_SECOND,
                        bits_per_second::to_tera_bytes_per_second,
                    ),
                ]),
            ),
            (
                GIGABITS_PER_SECOND,
                HashMap::from_iter([
                    (
                        BITS_PER_SECOND,
                        giga_bits_per_second::to_bits_per_second as ConversionFunction,
                    ),
                    (GIGABITS_PER_SECOND, identity),
                    (
                        GIGABYTES_PER_SECOND,
                        giga_bits_per_second::to_giga_bytes_per_second,
                    ),
                    (
                        KIBIBITS_PER_SECOND,
                        giga_bits_per_second::to_kibibits_per_second,
                    ),
                    (
                        KILOBITS_PER_SECOND,
                        giga_bits_per_second::to_kilo_bits_per_second,
                    ),
                    (
                        KILOBYTES_PER_SECOND,
                        giga_bits_per_second::to_kilo_bytes_per_second,
                    ),
                    (
                        MEBIBITS_PER_SECOND,
                        giga_bits_per_second::to_mebibits_per_second,
                    ),
                    (
                        MEGABITS_PER_SECOND,
                        giga_bits_per_second::to_mega_bits_per_second,
                    ),
                    (
                        MEGABYTES_PER_SECOND,
                        giga_bits_per_second::to_mega_bytes_per_second,
                    ),
                    (
                        TERABITS_PER_SECOND,
                        giga_bits_per_second::to_tera_bits_per_second,
                    ),
                    (
                        TERABYTES_PER_SECOND,
                        giga_bits_per_second::to_tera_bytes_per_second,
                    ),
                ]),
            ),
            (
                GIGABYTES_PER_SECOND,
                HashMap::from_iter([
                    (
                        BITS_PER_SECOND,
                        giga_bytes_per_second::to_bits_per_second as ConversionFunction,
                    ),
                    (
                        GIGABITS_PER_SECOND,
                        giga_bytes_per_second::to_giga_bits_per_second,
                    ),
                    (GIGABYTES_PER_SECOND, identity),
                    (
                        KIBIBITS_PER_SECOND,
                        giga_bytes_per_second::to_kibibits_per_second,
                    ),
                    (
                        KILOBITS_PER_SECOND,
                        giga_bytes_per_second::to_kilo_bits_per_second,
                    ),
                    (
                        KILOBYTES_PER_SECOND,
                        giga_bytes_per_second::to_kilo_bytes_per_second,
                    ),
                    (
                        MEBIBITS_PER_SECOND,
                        giga_bytes_per_second::to_mebibits_per_second,
                    ),
                    (
                        MEGABITS_PER_SECOND,
                        giga_bytes_per_second::to_mega_bits_per_second,
                    ),
                    (
                        MEGABYTES_PER_SECOND,
                        giga_bytes_per_second::to_mega_bytes_per_second,
                    ),
                    (
                        TERABITS_PER_SECOND,
                        giga_bytes_per_second::to_tera_bits_per_second,
                    ),
                    (
                        TERABYTES_PER_SECOND,
                        giga_bytes_per_second::to_tera_bytes_per_second,
                    ),
                ]),
            ),
            (
                KIBIBITS_PER_SECOND,
                HashMap::from_iter([
                    (
                        BITS_PER_SECOND,
                        kibibits_per_second::to_bits_per_second as ConversionFunction,
                    ),
                    (
                        GIGABITS_PER_SECOND,
                        kibibits_per_second::to_giga_bits_per_second,
                    ),
                    (
                        GIGABYTES_PER_SECOND,
                        kibibits_per_second::to_giga_bytes_per_second,
                    ),
                    (KIBIBITS_PER_SECOND, identity),
                    (
                        KILOBITS_PER_SECOND,
                        kibibits_per_second::to_kilo_bits_per_second,
                    ),
                    (
                        KILOBYTES_PER_SECOND,
                        kibibits_per_second::to_kilo_bytes_per_second,
                    ),
                    (
                        MEBIBITS_PER_SECOND,
                        kibibits_per_second::to_mebibits_per_second,
                    ),
                    (
                        MEGABITS_PER_SECOND,
                        kibibits_per_second::to_mega_bits_per_second,
                    ),
                    (
                        MEGABYTES_PER_SECOND,
                        kibibits_per_second::to_mega_bytes_per_second,
                    ),
                    (
                        TERABITS_PER_SECOND,
                        kibibits_per_second::to_tera_bits_per_second,
                    ),
                    (
                        TERABYTES_PER_SECOND,
                        kibibits_per_second::to_tera_bytes_per_second,
                    ),
                ]),
            ),
            (
                KILOBITS_PER_SECOND,
                HashMap::from_iter([
                    (
                        BITS_PER_SECOND,
                        kilo_bits_per_second::to_bits_per_second as ConversionFunction,
                    ),
                    (
                        GIGABITS_PER_SECOND,
                        kilo_bits_per_second::to_giga_bits_per_second,
                    ),
                    (
                        GIGABYTES_PER_SECOND,
                        kilo_bits_per_second::to_giga_bytes_per_second,
                    ),
                    (
                        KIBIBITS_PER_SECOND,
                        kilo_bits_per_second::to_kibibits_per_second,
                    ),
                    (KILOBITS_PER_SECOND, identity),
                    (
                        KILOBYTES_PER_SECOND,
                        kilo_bits_per_second::to_kilo_bytes_per_second,
                    ),
                    (
                        MEBIBITS_PER_SECOND,
                        kilo_bits_per_second::to_mebibits_per_second,
                    ),
                    (
                        MEGABITS_PER_SECOND,
                        kilo_bits_per_second::to_mega_bits_per_second,
                    ),
                    (
                        MEGABYTES_PER_SECOND,
                        kilo_bits_per_second::to_mega_bytes_per_second,
                    ),
                    (
                        TERABITS_PER_SECOND,
                        kilo_bits_per_second::to_tera_bits_per_second,
                    ),
                    (
                        TERABYTES_PER_SECOND,
                        kilo_bits_per_second::to_tera_bytes_per_second,
                    ),
                ]),
            ),
            (
                KILOBYTES_PER_SECOND,
                HashMap::from_iter([
                    (
                        BITS_PER_SECOND,
                        kilo_bytes_per_second::to_bits_per_second as ConversionFunction,
                    ),
                    (
                        GIGABITS_PER_SECOND,
                        kilo_bytes_per_second::to_giga_bits_per_second,
                    ),
                    (
                        GIGABYTES_PER_SECOND,
                        kilo_bytes_per_second::to_giga_bytes_per_second,
                    ),
                    (
                        KIBIBITS_PER_SECOND,
                        kilo_bytes_per_second::to_kibibits_per_second,
                    ),
                    (
                        KILOBITS_PER_SECOND,
                        kilo_bytes_per_second::to_kilo_bits_per_second,
                    ),
                    (KILOBYTES_PER_SECOND, identity),
                    (
                        MEBIBITS_PER_SECOND,
                        kilo_bytes_per_second::to_mebibits_per_second,
                    ),
                    (
                        MEGABITS_PER_SECOND,
                        kilo_bytes_per_second::to_mega_bits_per_second,
                    ),
                    (
                        MEGABYTES_PER_SECOND,
                        kilo_bytes_per_second::to_mega_bytes_per_second,
                    ),
                    (
                        TERABITS_PER_SECOND,
                        kilo_bytes_per_second::to_tera_bits_per_second,
                    ),
                    (
                        TERABYTES_PER_SECOND,
                        kilo_bytes_per_second::to_tera_bytes_per_second,
                    ),
                ]),
            ),
            (
                MEBIBITS_PER_SECOND,
                HashMap::from_iter([
                    (
                        BITS_PER_SECOND,
                        mebibits_per_second::to_bits_per_second as ConversionFunction,
                    ),
                    (
                        GIGABITS_PER_SECOND,
                        mebibits_per_second::to_giga_bits_per_second,
                    ),
                    (
                        GIGABYTES_PER_SECOND,
                        mebibits_per_second::to_giga_bytes_per_second,
                    ),
                    (
                        KIBIBITS_PER_SECOND,
                        mebibits_per_second::to_kibibits_per_second,
                    ),
                    (
                        KILOBITS_PER_SECOND,
                        mebibits_per_second::to_kilo_bits_per_second,
                    ),
                    (
                        KILOBYTES_PER_SECOND,
                        mebibits_per_second::to_kilo_bytes_per_second,
                    ),
                    (MEBIBITS_PER_SECOND, identity),
                    (
                        MEGABITS_PER_SECOND,
                        mebibits_per_second::to_mega_bits_per_second,
                    ),
                    (
                        MEGABYTES_PER_SECOND,
                        mebibits_per_second::to_mega_bytes_per_second,
                    ),
                    (
                        TERABITS_PER_SECOND,
                        mebibits_per_second::to_tera_bits_per_second,
                    ),
                    (
                        TERABYTES_PER_SECOND,
                        mebibits_per_second::to_tera_bytes_per_second,
                    ),
                ]),
            ),
            (
                MEGABITS_PER_SECOND,
                HashMap::from_iter([
                    (
                        BITS_PER_SECOND,
                        mega_bits_per_second::to_bits_per_second as ConversionFunction,
                    ),
                    (
                        GIGABITS_PER_SECOND,
                        mega_bits_per_second::to_giga_bits_per_second,
                    ),
                    (
                        GIGABYTES_PER_SECOND,
                        mega_bits_per_second::to_giga_bytes_per_second,
                    ),
                    (
                        KIBIBITS_PER_SECOND,
                        mega_bits_per_second::to_kibibits_per_second,
                    ),
                    (
                        KILOBITS_PER_SECOND,
                        mega_bits_per_second::to_kilo_bits_per_second,
                    ),
                    (
                        KILOBYTES_PER_SECOND,
                        mega_bits_per_second::to_kilo_bytes_per_second,
                    ),
                    (
                        MEBIBITS_PER_SECOND,
                        mega_bits_per_second::to_mebibits_per_second,
                    ),
                    (MEGABITS_PER_SECOND, identity),
                    (
                        MEGABYTES_PER_SECOND,
                        mega_bits_per_second::to_mega_bytes_per_second,
                    ),
                    (
                        TERABITS_PER_SECOND,
                        mega_bits_per_second::to_tera_bits_per_second,
                    ),
                    (
                        TERABYTES_PER_SECOND,
                        mega_bits_per_second::to_tera_bytes_per_second,
                    ),
                ]),
            ),
            (
                MEGABYTES_PER_SECOND,
                HashMap::from_iter([
                    (
                        BITS_PER_SECOND,
                        mega_bytes_per_second::to_bits_per_second as ConversionFunction,
                    ),
                    (
                        GIGABITS_PER_SECOND,
                        mega_bytes_per_second::to_giga_bits_per_second,
                    ),
                    (GIGABYTES_PER_SECOND, identity),
                    (
                        KIBIBITS_PER_SECOND,
                        mega_bytes_per_second::to_kibibits_per_second,
                    ),
                    (
                        KILOBITS_PER_SECOND,
                        mega_bytes_per_second::to_kilo_bits_per_second,
                    ),
                    (
                        KILOBYTES_PER_SECOND,
                        mega_bytes_per_second::to_kilo_bytes_per_second,
                    ),
                    (
                        MEBIBITS_PER_SECOND,
                        mega_bytes_per_second::to_mebibits_per_second,
                    ),
                    (
                        MEGABITS_PER_SECOND,
                        mega_bytes_per_second::to_mega_bits_per_second,
                    ),
                    (MEGABYTES_PER_SECOND, identity),
                    (
                        TERABITS_PER_SECOND,
                        mega_bytes_per_second::to_tera_bits_per_second,
                    ),
                    (
                        TERABYTES_PER_SECOND,
                        mega_bytes_per_second::to_tera_bytes_per_second,
                    ),
                ]),
            ),
            (
                TERABITS_PER_SECOND,
                HashMap::from_iter([
                    (
                        BITS_PER_SECOND,
                        tera_bits_per_second::to_bits_per_second as ConversionFunction,
                    ),
                    (
                        GIGABITS_PER_SECOND,
                        tera_bits_per_second::to_giga_bits_per_second,
                    ),
                    (
                        GIGABYTES_PER_SECOND,
                        tera_bits_per_second::to_giga_bytes_per_second,
                    ),
                    (
                        KIBIBITS_PER_SECOND,
                        tera_bits_per_second::to_kibibits_per_second,
                    ),
                    (
                        KILOBITS_PER_SECOND,
                        tera_bits_per_second::to_kilo_bits_per_second,
                    ),
                    (
                        KILOBYTES_PER_SECOND,
                        tera_bits_per_second::to_kilo_bytes_per_second,
                    ),
                    (
                        MEBIBITS_PER_SECOND,
                        tera_bits_per_second::to_mebibits_per_second,
                    ),
                    (
                        MEGABITS_PER_SECOND,
                        tera_bits_per_second::to_mega_bits_per_second,
                    ),
                    (
                        MEGABYTES_PER_SECOND,
                        tera_bits_per_second::to_mega_bytes_per_second,
                    ),
                    (TERABITS_PER_SECOND, identity),
                    (
                        TERABYTES_PER_SECOND,
                        tera_bits_per_second::to_tera_bytes_per_second,
                    ),
                ]),
            ),
            (
                TERABYTES_PER_SECOND,
                HashMap::from_iter([
                    (
                        BITS_PER_SECOND,
                        tera_bytes_per_second::to_bits_per_second as ConversionFunction,
                    ),
                    (
                        GIGABITS_PER_SECOND,
                        tera_bytes_per_second::to_giga_bits_per_second,
                    ),
                    (
                        GIGABYTES_PER_SECOND,
                        tera_bytes_per_second::to_giga_bytes_per_second,
                    ),
                    (
                        KIBIBITS_PER_SECOND,
                        tera_bytes_per_second::to_kibibits_per_second,
                    ),
                    (
                        KILOBITS_PER_SECOND,
                        tera_bytes_per_second::to_kilo_bits_per_second,
                    ),
                    (
                        KILOBYTES_PER_SECOND,
                        tera_bytes_per_second::to_kilo_bytes_per_second,
                    ),
                    (
                        MEBIBITS_PER_SECOND,
                        tera_bytes_per_second::to_mebibits_per_second,
                    ),
                    (
                        MEGABITS_PER_SECOND,
                        tera_bytes_per_second::to_mega_bits_per_second,
                    ),
                    (
                        MEGABYTES_PER_SECOND,
                        tera_bytes_per_second::to_mega_bytes_per_second,
                    ),
                    (
                        TERABITS_PER_SECOND,
                        tera_bytes_per_second::to_tera_bits_per_second,
                    ),
                    (TERABYTES_PER_SECOND, identity),
                ]),
            ),
        ])
    }
}
